language: python
python:
  - "3.6"
install:
  - pip install tensorflow
  - pip install numpy
  - pip install matplotlib
  - pip install tensorflow_datasets
script:
  - python CelsiusToFahernheit.py
  - python fashionMnistDataset.py
